/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    dev: [
        {
            type: 'autogenerated',
            dirName: 'dev',
        },
    ],
    db: [
        {
            type: 'autogenerated',
            dirName: 'db',
        },
    ],
    devops: [
        {
            type: 'autogenerated',
            dirName: 'devops',
        },
    ],
    os: [
        {
            type: 'autogenerated',
            dirName: 'os',
        },
    ],
    design: [
        {
            type: 'autogenerated',
            dirName: 'design',
        },
    ],
    testing: [
        {
            type: 'autogenerated',
            dirName: 'testing',
        },
    ],
    gis: [
        {
            type: 'autogenerated',
            dirName: 'gis',
        },
    ],
    server: [
        {
            type: 'autogenerated',
            dirName: 'server',
        },
    ],
    editor: [
        {
            type: 'autogenerated',
            dirName: 'editor',
        },
    ],
};

module.exports = sidebars;
